# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_DRM_NEBULAE) += nebulae.o

nebulae-y := \
	nebulae_drv.o \
	nebulae_device.o \
	nebulae_gem.o \
	nebulae_vm.o \
	nebulae_mmu.o \
	nebulae_ctx.o \
	nebulae_sched.o \
	nebulae_submit.o \
	nebulae_irq.o \
	nebulae_recovery.o \
	nebulae_trace.o \
	nebulae_debugfs.o \
	nebulae_sysfs.o \
	nebulae_kms.o \
	nebulae_crtc.o \
	nebulae_plane.o \
	nebulae_output.o \
	nebulae_fb.o \
	nebulae_vblank.o
