/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef NEBULAE_REGS_H
#define NEBULAE_REGS_H

#define NEB_REG_MAGIC			0x0000
#define NEB_REG_VERSION			0x0004
#define NEB_REG_CAPS			0x0008
#define NEB_REG_CONTROL			0x0010
#define NEB_REG_STATUS			0x0014
#define NEB_REG_IRQ_STATUS		0x0018
#define NEB_REG_IRQ_MASK		0x001c
#define NEB_REG_VRAM_SIZE_LO		0x0020
#define NEB_REG_VRAM_SIZE_HI		0x0024
#define NEB_REG_SUBMIT_OFFSET_LO	0x0030
#define NEB_REG_SUBMIT_OFFSET_HI	0x0034
#define NEB_REG_SUBMIT_SIZE		0x0038
#define NEB_REG_DOORBELL		0x003c
#define NEB_REG_JOB_SEQ_LO		0x0040
#define NEB_REG_JOB_SEQ_HI		0x0044
#define NEB_REG_COMPLETED_SEQ_LO	0x0048
#define NEB_REG_COMPLETED_SEQ_HI	0x004c
#define NEB_REG_LAST_ERROR		0x0050
#define NEB_REG_JOB_CONTROL_SEQ_LO	0x0058
#define NEB_REG_JOB_CONTROL_SEQ_HI	0x005c
#define NEB_REG_JOB_CONTROL		0x0060
#define NEB_REG_TLB_INVALIDATE		0x0064
#define NEB_REG_ICACHE_INVALIDATE	0x0068

/* Planned display controller registers for native KMS scanout. */
#define NEB_REG_DISPLAY_ENABLE		0x0100
#define NEB_REG_DISPLAY_WIDTH		0x0104
#define NEB_REG_DISPLAY_HEIGHT		0x0108
#define NEB_REG_DISPLAY_STRIDE		0x010c
#define NEB_REG_DISPLAY_FORMAT		0x0110
#define NEB_REG_DISPLAY_FB_BASE_LO	0x0114
#define NEB_REG_DISPLAY_FB_BASE_HI	0x0118
#define NEB_REG_DISPLAY_FB_SIZE		0x011c
#define NEB_REG_DISPLAY_FLIP		0x0120
#define NEB_REG_DISPLAY_IRQ_STATUS	0x0124
#define NEB_REG_DISPLAY_IRQ_MASK	0x0128
#define NEB_REG_DISPLAY_PLANE_BASE_LO	0x012c
#define NEB_REG_DISPLAY_PLANE_BASE_HI	0x0130
#define NEB_REG_DISPLAY_PLANE_STRIDE	0x0134
#define NEB_REG_DISPLAY_PLANE_FORMAT	0x0138
#define NEB_REG_DISPLAY_PLANE_FLAGS	0x013c
#define NEB_REG_DISPLAY_PLANE_SIZE	0x0140

#define NEB_MAGIC			0x584c424e
#define NEB_CONTROL_RESET		BIT(0)
#define NEB_STATUS_READY		BIT(0)
#define NEB_STATUS_BUSY			BIT(1)
#define NEB_STATUS_FAULT		BIT(2)
#define NEB_HW_STATUS_OK		0
#define NEB_HW_STATUS_INVALID_ARGUMENT	1
#define NEB_HW_STATUS_OUT_OF_RANGE	2
#define NEB_HW_STATUS_UNSUPPORTED	3
#define NEB_HW_STATUS_FAULT		4
#define NEB_HW_STATUS_CANCELLED		6
#define NEB_HW_STATUS_KILLED		7
#define NEB_CAP_NDRANGE		BIT(0)
#define NEB_CAP_IRQ			BIT(1)
#define NEB_CAP_SYNC_VRAM		BIT(2)
#define NEB_CAP_TLB_INVALIDATE		BIT(3)
#define NEB_CAP_CP_QUEUE		BIT(4)
#define NEB_CAP_JOB_CONTROL		BIT(5)
#define NEB_CAP_FULL_GPUVM		BIT(6)
#define NEB_CAP_ICACHE_INVALIDATE	BIT(7)
#define NEB_CAP_CP_RESOURCE_OWNERSHIP	BIT(8)
#define NEB_JOB_CONTROL_CANCEL		BIT(0)
#define NEB_JOB_CONTROL_KILL		BIT(1)
#define NEB_TLB_INVALIDATE_ALL		BIT(0)
#define NEB_ICACHE_INVALIDATE_ALL	BIT(0)
#define NEB_IRQ_COMPLETE		BIT(0)
#define NEB_IRQ_FAULT			BIT(1)
#define NEB_IRQ_DISPLAY			BIT(2)
#define NEB_IRQ_ALL			(NEB_IRQ_COMPLETE | NEB_IRQ_FAULT | \
					 NEB_IRQ_DISPLAY)

#define NEB_DISPLAY_FORMAT_XRGB8888	1
#define NEB_DISPLAY_FORMAT_RGBA8888	2
#define NEB_DISPLAY_FORMAT_BGRA8888	3
#define NEB_DISPLAY_PLANE_VALID		BIT(0)
#define NEB_DISPLAY_PLANE_Y_FLIP	BIT(1)
#define NEB_DISPLAY_IRQ_FLIP_DONE	BIT(0)

#endif /* NEBULAE_REGS_H */
